# This is a basic workflow to help you get started with Actions

name: Build Lambda Packages and upload it to s3
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master , build-packages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    outputs:
      output1: ${{ steps.find_changes.outputs.test }}
    steps:
      #- run: echo ${{secrets.AWS_ACCESS_KEY_ID_TEST}}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true
      - name: Checkout Dependencies Repo
        uses: actions/checkout@v2
        with:
          repository: cmc-ai/payment-processor
          ref: main
          path: payment-processor
          token: ${{ secrets.IAC_PAT }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Find changes
        run: echo "::set-output name=test::["1", "2", "3"]"
        id: find_changes

  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{needs.build.outputs.output1}}
